
services:
  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - post-api-1
      - post-api-2
      - minitwitter-frontend
  
  my-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  post-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-api-1
    environment: 
      DATABASE_URL: postgresql://postgres:supersecret123@my-postgres:5432/minitwitter
    ports:
      - "3001:3000"
    command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    depends_on:
      my-postgres:
        condition: service_healthy
    networks:
      - app-network

  post-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-api-2
    environment: 
      DATABASE_URL: postgresql://postgres:supersecret123@my-postgres:5432/minitwitter
    ports:
      - "3002:3000"
    command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    depends_on:
      my-postgres:
        condition: service_healthy
    networks:
      - app-network

  minitwitter-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: minitwitter-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - post-api-1
      - post-api-2

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

# Use a base image with Node.js
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the application
CMD ["npm", "run", "prod"]

{
  "scripts": {
    "build": "tsc && npm run build",
    "prod": "node dist/app.js"
  }
}