name: minitwitter
services:
  load-balancer:
    image: nginx
    container_name: load-balancer
    ports:
      - 90:90
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  my-postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  Post-API-1:
    image: adi-image 
    environment: 
      DATABASE_URL: postgresql://postgres:supersecret123@my-postgres:5432/minitwitter
    command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    depends_on:
      - my-postgres
    
  Post-API-2:
    image: adi-image 
    environment: 
      DATABASE_URL: postgresql://postgres:supersecret123@my-postgres:5432/minitwitter
    command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    depends_on:
      - my-postgres

  minitwitter-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:80

      