services:
  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - post-api-1
      - post-api-2
      - minitwitter-frontend
  
  my-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  post-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-api-1
    environment: 
      DATABASE_URL: postgresql://postgres:supersecret123@my-postgres:5432/minitwitter
    ports:
      - "3001:3000"
    command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    networks:
      - app-network

  post-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-api-2
    environment: 
      DATABASE_URL: postgresql://postgres:supersecret123@my-postgres:5432/minitwitter
    ports:
      - "3002:3000"
    command: /bin/sh -c "bunx drizzle-kit push && bun run prod"
    networks:
      - app-network

  minitwitter-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: minitwitter-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - post-api-1
      - post-api-2
      
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "12434:11434"
    volumes:
      - ./docker-data/ollama:/root/.ollama
    networks:
      - app-network

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
